import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  getCantonStatus,
  fundBountyOnLedger,
  claimBountyOnLedger,
  approveBountyOnLedger,
  settleBountyOnLedger,
  getActiveLedgerBounties,
} from './server/client';
import { getCantonConfig } from './server/config';
import type { Bounty, Party } from '@/domain/bounty';

// Force real Canton participant mode for live integration test
process.env.CANTON_INTEGRATION_MODE = 'real';

test('1. Live Canton participant is connected and responsive', async () => {
  const status = await getCantonStatus();
  assert.equal(status.mode, 'real');
  assert.equal(status.connected, true, `Canton participant at ${status.ledgerApiUrl} must be reachable. Error: ${status.error}`);
  assert.equal(status.network, 'Canton LocalNet');
});

test('2. Package is deployed and parties exist on live Canton ledger', async () => {
  const cfg = getCantonConfig();
  const status = await getCantonStatus();
  
  // Verify package on participant
  const pkgRes = await fetch(`${cfg.ledgerApiUrl}/v2/packages/${cfg.packageId}`);
  assert.equal(pkgRes.status, 200, `MergeMint DAR package ${cfg.packageId} must be uploaded to participant`);

  // Verify CIP-56 Splice Holding interface package on participant
  const tokenPkgRes = await fetch(`${cfg.ledgerApiUrl}/v2/packages/${cfg.tokenPackageId}`);
  assert.equal(tokenPkgRes.status, 200, `Splice Holding DAR package ${cfg.tokenPackageId} must be uploaded to participant`);

  // Verify parties on participant
  const partiesRes = await fetch(`${cfg.ledgerApiUrl}/v2/parties`);
  assert.equal(partiesRes.status, 200);
  const data = (await partiesRes.json()) as { partyDetails: Array<{ party: string }> };
  const partyList = data.partyDetails.map(p => p.party);

  assert.ok(partyList.includes(status.parties.sponsor.partyId), `Sponsor party ${status.parties.sponsor.partyId} must exist`);
  assert.ok(partyList.includes(status.parties.maintainer.partyId), `Maintainer party ${status.parties.maintainer.partyId} must exist`);
  assert.ok(partyList.includes(status.parties.contributor.partyId), `Contributor party ${status.parties.contributor.partyId} must exist`);
});

test('3. Full on-ledger bounty lifecycle executes against real Canton JSON Ledger API with Level C CIP-56 Holding-compatible Token Transfer', async () => {
  const status = await getCantonStatus();
  const bountyId = `bounty-live-${Date.now()}`;
  const sha = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';

  const sponsor: Party = status.parties.sponsor;
  const maintainer: Party = status.parties.maintainer;
  const contributor: Party = status.parties.contributor;

  const bounty: Bounty = {
    id: bountyId,
    repo: 'mergemint/core',
    issue: 101,
    title: 'Live Canton Ledger Verification',
    amount: '500',
    asset: 'MMT',
    sponsor,
    maintainer,
    criteria: ['Execute on real Canton participant', 'Archive previous contract on choice'],
    status: 'DRAFT',
    activity: 'Initiating live Canton test',
  };

  // Step A: Fund on Canton participant + Lock Level C Token Holding
  const fundResult = await fundBountyOnLedger(bounty);
  assert.ok(fundResult.contractId, 'Real contract ID must be returned');
  assert.ok(fundResult.transactionId, 'Real transaction/update ID must be returned');
  assert.ok(fundResult.tokenHoldingId, 'CIP-56 token holding contract ID must be created');
  assert.equal(fundResult.status, 'FUNDED');

  // Verify ACS contains newly created contract
  let activeContracts = await getActiveLedgerBounties();
  let found = activeContracts.find(c => c.bountyId === bountyId && c.status !== 'SETTLED');
  assert.ok(found, 'Created bounty must be present in Canton ACS');
  assert.equal(found.status, 'FUNDED');
  assert.equal(found.contractId, fundResult.contractId);
  assert.ok(found.tokenHoldingContractId, 'Bounty contract must link locked token holding contract ID');

  // Step B: Claim choice on Canton participant (consuming choice)
  const claimResult = await claimBountyOnLedger(bountyId, contributor);
  assert.ok(claimResult.contractId, 'New contract ID must be generated by Canton consuming choice');
  assert.notEqual(claimResult.contractId, fundResult.contractId, 'Previous contract must be archived');
  assert.equal(claimResult.status, 'CLAIMED');

  // Verify ACS reflects CLAIMED state
  activeContracts = await getActiveLedgerBounties();
  found = activeContracts.find(c => c.bountyId === bountyId && c.status !== 'SETTLED');
  assert.ok(found, 'Claimed bounty must exist in ACS');
  assert.equal(found.status, 'CLAIMED');
  assert.equal(found.contributor, contributor.partyId);

  // Step C: Approve choice on Canton participant
  const bountyWithContributor: Bounty = {
    ...bounty,
    contributor,
    fundingRef: claimResult.contractId,
    status: 'CLAIMED',
  };
  const approveResult = await approveBountyOnLedger(bountyWithContributor, sha, maintainer);
  assert.ok(approveResult.contractId);
  assert.notEqual(approveResult.contractId, claimResult.contractId, 'Previous contract must be archived on approval');
  assert.equal(approveResult.status, 'APPROVED');

  // Verify ACS reflects APPROVED state
  activeContracts = await getActiveLedgerBounties();
  found = activeContracts.find(c => c.bountyId === bountyId && c.status !== 'SETTLED');
  assert.ok(found, 'Approved bounty must exist in ACS');
  assert.equal(found.status, 'APPROVED');
  assert.equal(found.submissionSha, sha);

  // Step D: Settle choice + Transfer Token Holding atomically on Canton
  const approvedBounty: Bounty = {
    ...bountyWithContributor,
    status: 'APPROVED',
    tokenHoldingContractId: fundResult.tokenHoldingId,
    approval: {
      sha,
      maintainerId: maintainer.partyId,
      approvedAt: new Date().toISOString(),
    },
  };
  const settleResult = await settleBountyOnLedger(approvedBounty);
  assert.ok(settleResult.contractId, 'SettledReceipt contract ID must be returned');
  assert.equal(settleResult.status, 'SETTLED');
  assert.ok(settleResult.tokenHoldingId, 'Original token holding ID must be referenced');
  assert.ok(settleResult.tokenTransferId, 'Token transfer update ID must be returned');

  // Verify ACS: MergeMintBounty is completely archived/consumed, only SettledReceipt remains
  activeContracts = await getActiveLedgerBounties();
  const unSettled = activeContracts.find(c => c.bountyId === bountyId && c.status !== 'SETTLED');
  assert.equal(unSettled, undefined, 'Active MergeMintBounty must be archived from Canton ACS upon settlement');

  const receipt = activeContracts.find(c => c.bountyId === bountyId && c.status === 'SETTLED');
  assert.ok(receipt, 'SettledReceipt must be present in Canton ACS');
  assert.equal(receipt.settledReceipt?.approvedSha, sha);

  // Step E: Verify live on-chain balances reflect transferred CIP-56 token holding
  const finalStatus = await getCantonStatus();
  assert.ok(finalStatus.balances, 'Balances must be calculated from Canton ACS');
  assert.ok(Number(finalStatus.balances.contributor) >= 500, 'Contributor must receive transferred CIP-56 token holding');

  // Step F: Directly query Canton ACS with CIP-56 Splice Holding interface filter
  const cfg = getCantonConfig();
  const spliceAcsRes = await fetch(`${cfg.ledgerApiUrl}/v2/state/active-contracts-page`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      eventFormat: {
        filtersForAnyParty: {
          cumulative: [
            {
              interfaceFilter: {
                interfaceId: `${cfg.tokenPackageId}:Splice.Api.Token.HoldingV1:Holding`,
                includeView: true,
              },
            },
          ],
        },
        verbose: true,
      },
    }),
  });
  assert.equal(spliceAcsRes.status, 200);
  const spliceAcsData = (await spliceAcsRes.json()) as { activeContracts?: Array<{ contractEntry?: { JsActiveContract?: { createdEvent?: { contractId: string; templateId: string } } } }> };
  const contributorHoldings = (spliceAcsData.activeContracts || []).filter(c =>
    c.contractEntry?.JsActiveContract?.createdEvent?.templateId?.includes('MergeMintHolding')
  );
  assert.ok(contributorHoldings.length > 0, 'MergeMintHolding must be registered and queryable under the official Splice HoldingV1 interface');
});
