import { test } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { getCantonConfig } from './server/config';
import { fundBountyOnLedger, claimBountyOnLedger, approveBountyOnLedger, settleBountyOnLedger, queryLedgerActiveContracts, queryLedgerBalances, queryRawLedgerContracts, submitLedgerCommand } from './server/client';
import { revision, units, template } from './server/ledger';
import type { Bounty } from '@/domain/bounty';

process.env.CANTON_INTEGRATION_MODE = 'real';
test('Fresh LocalNet: existing value -> locked bounty -> exact approval -> recipient holding; negative ledger guards', async () => {
 const cfg=getCantonConfig();
 assert.equal(new URL(cfg.ledgerApiUrl).hostname,'127.0.0.1','Live tests are restricted to loopback LocalNet.');
 const before=await queryLedgerBalances();
 const b:Bounty={id:`correctness-${crypto.randomUUID()}`,repo:'grzdev/mergemint',issue:1,title:'LocalNet contract proof (synthetic GitHub evidence)',amount:'12.3456789012',asset:'MMT',sponsor:cfg.parties.sponsor,maintainer:cfg.parties.maintainer,criteria:['Conserve existing MMT; bind payout to exact approval'],status:'DRAFT',activity:'test'};
 const funded=await fundBountyOnLedger(b);
 assert.equal(funded.tokenHoldingId,funded.contractId,'The bounty itself is the locked holding.');
 const afterFund=await queryLedgerBalances();
 assert.equal(units(before.sponsor)-units(afterFund.sponsor),units(b.amount));
 assert.equal(units(afterFund.escrow)-units(before.escrow),units(b.amount));
 await assert.rejects(fundBountyOnLedger({...b,id:`too-large-${crypto.randomUUID()}`,amount:'999999999'}),/Insufficient/);
 async function rawChoice(id:string,choice:string,args:Record<string,unknown>,actors:string[]) { return submitLedgerCommand(actors,[],{ExerciseCommand:{templateId:template('MergeMintBounty'),contractId:id,choice,choiceArgument:args}},crypto.randomUUID(),'negative-proof'); }
 await assert.rejects(rawChoice(funded.contractId,'Archive',{},[b.sponsor.partyId]),'Sponsor alone cannot archive locked value.');
 await assert.rejects(rawChoice(funded.contractId,'Transfer',{newOwner:cfg.parties.contributor.partyId},[b.sponsor.partyId]),'Locked bounty has no transfer bypass.');
 const claimed=await claimBountyOnLedger(b.id,cfg.parties.contributor);
 await assert.rejects(claimBountyOnLedger(b.id,cfg.parties.contributor));
 const sha='a'.repeat(40), newer='b'.repeat(40);
 b.contributor=cfg.parties.contributor;
 b.submission={number:1,title:'Synthetic PR for contract testing',branch:'test',sha,merged:false,review:'test',checks:[]};
 b.status='SUBMITTED';
 await assert.rejects(rawChoice(claimed.contractId,'Settle',{settler:b.maintainer.partyId,sha,settlementRef:'unapproved'},[b.maintainer.partyId]));
 const approved=await approveBountyOnLedger(b,sha,b.maintainer);
 b.approval={sha,maintainerId:b.maintainer.partyId,approvedAt:new Date().toISOString()};
 await assert.rejects(rawChoice(approved.contractId,'Settle',{settler:b.maintainer.partyId,sha:newer,settlementRef:'wrong-revision'},[b.maintainer.partyId]));
 await assert.rejects(rawChoice(approved.contractId,'Settle',{settler:b.sponsor.partyId,sha,settlementRef:'wrong-actor'},[b.sponsor.partyId]));
 await revision(b.id,newer,1);
 await assert.rejects(settleBountyOnLedger(b),/approval/);
 b.submission.sha=newer; b.approval=undefined;
 await approveBountyOnLedger(b,newer,b.maintainer);
 b.approval={sha:newer,maintainerId:b.maintainer.partyId,approvedAt:new Date().toISOString()};
 const settled=await settleBountyOnLedger(b);
 assert.ok(settled.tokenRecipientHoldingId);
 assert.equal(settled.reference,settled.transactionId,'UI reference is a real ledger update ID.');
 const raw=await queryRawLedgerContracts();
 const holding=raw.map(x=>x.contractEntry?.JsActiveContract?.createdEvent).find(e=>e?.contractId===settled.tokenRecipientHoldingId);
 assert.equal(holding?.createArgument.owner,b.contributor.partyId);
 assert.equal(units(String(holding?.createArgument.amount)),units(b.amount));
 const receipts=(await queryLedgerActiveContracts()).filter(c=>c.bountyId===b.id);
 assert.equal(receipts.length,1); assert.equal(receipts[0].status,'SETTLED');
 assert.equal(receipts[0].settledReceipt?.tokenRecipientHoldingId,settled.tokenRecipientHoldingId);
 await assert.rejects(settleBountyOnLedger(b));
 const after=await queryLedgerBalances();
 assert.equal(units(after.escrow),units(before.escrow));
 assert.equal(units(after.contributor)-units(before.contributor),units(b.amount));
 assert.equal(units(after.sponsor)+units(after.contributor)+units(after.escrow),units(before.sponsor)+units(before.contributor)+units(before.escrow));
 console.log(JSON.stringify({bountyId:b.id,transactionId:settled.transactionId,receiptId:settled.contractId,recipientHoldingId:settled.tokenRecipientHoldingId,amount:b.amount,approvedSha:newer,syntheticGitHubEvidence:true}));
});
