canton {
  sequencers.sequencer1 {
    storage.type = memory
    public-api { address = "127.0.0.1", port = 5011 }
    admin-api { address = "127.0.0.1", port = 5012 }
  }
  mediators.mediator1 {
    storage.type = memory
    admin-api { address = "127.0.0.1", port = 5212 }
  }
  participants.participant1 {
    storage.type = memory
    admin-api { address = "127.0.0.1", port = 14112 }
    ledger-api { address = "127.0.0.1", port = 14111 }
    http-ledger-api { address = "127.0.0.1", port = 7675 }
  }
}
